<?php
//
// File generated by Dolibarr installer 11.0.0 on 18 Fév. 2020
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
if($_SERVER['SERVER_ADDR']=="127.0.0.1"){ //config locale
    date_default_timezone_set('America/Martinique');
    $dolibarr_main_url_root='http://cara.ddns.net';
    $dolibarr_main_document_root='/Users/stanleydormoy/cloudweb/cara/htdocs';
    $dolibarr_main_url_root_alt='/custom';
    $dolibarr_main_document_root_alt='/Users/stanleydormoy/cloudweb/cara/htdocs/custom';
    $dolibarr_main_data_root='/Users/stanleydormoy/cloudweb/cara/documents';
    $dolibarr_main_db_host='127.0.0.1';
    $dolibarr_main_db_port='3306';
    $dolibarr_main_db_name='cara';
    $dolibarr_main_db_prefix='llx_';
    $dolibarr_main_db_user='root';
    $dolibarr_main_db_pass='france2584';
    $dolibarr_main_db_type='mysqli';
    $dolibarr_main_db_character_set='utf8';
    $dolibarr_main_db_collation='utf8_general_ci';
    // Authentication settings
    //$dolibarr_main_authentication='dolibarr';
    $dolibarr_main_authentication = 'mc';
    //$dolibarr_main_demo='autologin,autopass';
    // Security settings
    $dolibarr_main_prod='0';
    $dolibarr_main_force_https='0';
    $dolibarr_main_restrict_os_commands='mysqldump, mysql, pg_dump, pgrestore';
    $dolibarr_nocsrfcheck='0';
    $dolibarr_main_instance_unique_id='4d143fc47e08c9275d304edb3bc9f1e1';
    $dolibarr_mailing_limit_sendbyweb='0';
}
else{
    date_default_timezone_set('America/Martinique');
    $dolibarr_main_url_root='http://cara972.ddns.net';
    $dolibarr_main_document_root='/volume2/web/cara/htdocs';
    $dolibarr_main_url_root_alt='/custom';
    $dolibarr_main_document_root_alt='/volume2/web/cara/htdocs/custom';
    $dolibarr_main_data_root='/volume2/web/cara/documents';
    $dolibarr_main_db_host='localhost';
    $dolibarr_main_db_port='3306';
    $dolibarr_main_db_name='cara';
    $dolibarr_main_db_prefix='llx_';
    $dolibarr_main_db_user='root';
    $dolibarr_main_db_pass='france2584';
    $dolibarr_main_db_type='mysqli';
    $dolibarr_main_db_character_set='utf8';
    $dolibarr_main_db_collation='utf8_general_ci';
    // Authentication settings
    //$dolibarr_main_authentication='dolibarr';
    $dolibarr_main_authentication = 'mc';
    //$dolibarr_main_demo='autologin,autopass';
    // Security settings
    $dolibarr_main_prod='0';
    $dolibarr_main_force_https='0';
    $dolibarr_main_restrict_os_commands='mysqldump, mysql, pg_dump, pgrestore';
    $dolibarr_nocsrfcheck='0';
    $dolibarr_main_instance_unique_id='b1ab67381c6bdc55a85fa18cf5d48f65';
    $dolibarr_mailing_limit_sendbyweb='0';


}
//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_TCPDI_PATH='';
//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
